export const GET_RUBUSD_CURRENCY = 'GET_RUBUSD_CURRENCY';
export const GET_RUBUSD_CURRENCY_PENDING = 'GET_RUBUSD_CURRENCY_PENDING';
export const GET_RUBUSD_CURRENCY_FULFILLED = 'GET_RUBUSD_CURRENCY_FULFILLED';
export const GET_RUBUSD_CURRENCY_REJECTED = 'GET_RUBUSD_CURRENCY_REJECTED';