export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const GET_CURRENT_WEATHER_PENDING = 'GET_CURRENT_WEATHER_PENDING';
export const GET_CURRENT_WEATHER_FULFILLED = 'GET_CURRENT_WEATHER_FULFILLED';
export const GET_CURRENT_WEATHER_REJECTED = 'GET_CURRENT_WEATHER_REJECTED';